version: '3.9'

services:
    apache2:
        # 이미지를 다운로드하고 아파치 웹 서버 컨테이너를 시작합니다. 
        image: httpd:latest
        container_name: apache2
        # 컨테이너의 80번 포트는 호스트의 8000번 포트와 매핑
        ports:
            - "8000:80"
        volumes:
            # ./Project 디렉토리는 컨테이너의 /var/www/html 디렉토리와 공유
            - ./Project:/var/www/html #프로젝트 경로
            - ./apache2/conf:/usr/local/apache2/conf #apache2 설정파일
            #- ./apache2/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf #apache2 가상호스트 파일

    mariadb:
          container_name: mariadb
          image: mariadb:latest
          restart: always
          ports:
                  - 3306:3306
          volumes:
                  - "./mariadb/conf.d:/etc/mysql/conf.d"
                  - "./mariadb/data:/var/lib/mysql"
          environment:
                  MARIADB_DATABASE: {사용할 DB}
                  MARIADB_USER: {사용자 ID}
                  MARIADB_PASSWORD: {사용자 비밀번호}
                  MARIADB_ROOT_PASSWORD: {마리아DB 루트유저의 비밀번호}
          restart: always